### ISSUE TITLE
Wrong display name of UpgradeMicronautMavenPropertyVersion

### ISSUE THREAD

**Issue by csemrau** [openrewrite/rewrite-micronaut#33]
`UpgradeMicronautMavenPropertyVersion` updates the Maven configuration, not the Gradle configuration.

https://github.com/openrewrite/rewrite-micronaut/blob/main/src/main/java/org/openrewrite/java/micronaut/UpgradeMicronautMavenPropertyVersion.java#L47

**Comment by aegershman** [comment]
Right on, good catch, thanks @csemrau -- should be fixed by https://github.com/openrewrite/rewrite-micronaut/commit/970a6b08331d895d085cb6710d6ed2cc9cbdeb0c

Going to close this, feel free to either direct PR or comment @ me if this otherwise doesn't look like what you had in mind. Thanks again 👍
