### ISSUE TITLE
rewrite erroneously changes package names for jsr305

### ISSUE THREAD

**Issue by wetted** [openrewrite/rewrite-micronaut#35]
I have a java class that uses `com.google.code.findbugs:jsr305:3.0.2`

```Java
import javax.annotation.concurrent.Immutable;

@Immutable
...
```

The `rewrite-micronaut` recipe erroneously changes the import to `jakarta.annotation.concurrent.Immutable`

**Comment by aegershman** [comment]
Hey @wetted -- Thanks for reporting this. What version of the `rewrite-maven-plugin` (or `rewrite-gradle-plugin`) are you using + what version of the `rewrite-micronaut` dependency are you using?

If the versions are behind, could you try bumping the version of the plugins and rewrite-micronaut dependency to the latest release versions and re-run it?

**Comment by wetted** [comment]
@aegershman 

I was using 5.14.0 of the gradle plugin and 1.3.0 of the Micronaut rewrite recipe. I upgraded to the latest recipe, v1.4.0 and that seems to resolve the issue for me.

Sorry for the false alarm. I just used the example config given by https://docs.openrewrite.org/tutorials/migrate-to-micronaut-3-from-micronaut-2#example-configuration. You might want update that example documentation to reflect the latest recipe version.

**Comment by aegershman** [comment]
No need for apologies, thank you for reporting this-- we should have displayed the updated version out there. I'm going to update that documentation now. I'll go ahead and close this out, though 👍  Feel free to open issues, we appreciate it
