### ISSUE TITLE
Recipe for upgrade to Micronaut 4

### ISSUE THREAD

**Issue by jeremyg484** [openrewrite/rewrite-micronaut#49]
I am a member of the Micronaut development team and we are currently investigating providing OpenRewrite support in a timely fashion for upgrading from Micronaut 3 to Micronaut 4 (which is currently in the milestone release phase with a final release imminently approaching). Reference https://github.com/micronaut-projects/micronaut-core/issues/9214

I am currently in-progress with a from-scratch recipe as the unit tests in this repo (as well as the in the branch for the pending OpenRewrite 8 upgrade PR) seem to be broken, but our preference long-term would be to contribute the new recipe here. The new recipe WIP resides here: https://github.com/jeremyg484/rewrite-micronaut4

We have so far encountered some issues while creating the new recipe - see https://github.com/openrewrite/rewrite/issues/3255 and https://github.com/openrewrite/rewrite/issues/3256

Please let me know your thoughts on how we should proceed in merging/contributing the new recipe here.

**Comment by timtebeek** [comment]
Hi @jeremyg484; Good seeing you here! I'd been meaning to reach out after talking to Álvaro in March; would love to work together to support your upcoming release. I've sent you an invite to collaborate in this repository; I can further elevate your privileges if you want to invite others.

Welcome to open draft pull request here such that we can have a look as well; we're working towards a 8.0 release with some required changes. We can help you adopt those changes such that it'll all work, and can be released in tandem with your and our releases.

Glad to see the two issues that you mentioned have already been resolved; do let us know if there's anything else blocking you. Also welcome to reach out via Slack if there's anything you'd like to discuss!

**Comment by jeremyg484** [comment]
@timtebeek Awesome, sounds good! I've got a bit more work to do to get the new recipe(s) into a good enough initial state (basically covering everything in https://micronaut.io/2023/05/09/upgrade-to-micronaut-framework-4-0-0/) and then I will begin looking at how to merge the code into this repo and send that PR.

**Comment by timtebeek** [comment]
Great! I've added both of you as writers to this project; again; let me know if you need more privileges or people added.
We also have a [Slack channel](https://rewriteoss.slack.com/join/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA#/shared-invite/email) if that helps with any questions or suggestions you might have. Looking forward to collaborating!

**Comment by timtebeek** [comment]
Perhaps good to note here as well: We're nearing an 8.0 release with some breaking changes; a preview of those changes as applied to this repository is already in: https://github.com/openrewrite/rewrite-micronaut/pull/48 ; There's some background to these changes in https://github.com/openrewrite/rewrite/issues/3234 ; in short we've had to accommodate the Drools folks showing up with 200+ Maven modules. ;)

If you want to already build against our 8.0 branch you can locally [checkout the large repositories branch](https://github.com/openrewrite/rewrite/tree/large-repositories) and then run `./gradlew publishToMavenLocal`. We're close to merging this, but then we've also been saying that for two weeks by now. 🤞🏻 Let me know if you need any help!
