### ISSUE TITLE
Some APIs require specifiying HTTPRequest as a generic

### ISSUE THREAD

**Issue by sdelamo** [openrewrite/rewrite-micronaut#63]
Code such as: 

```java

import io.micronaut.security.authentication.AuthenticationProvider;

@Singleton // <1>
public class AuthenticationProviderUserPassword implements AuthenticationProvider { 
```

becomes: 

```java
import io.micronaut.security.authentication.AuthenticationProvider;

@Singleton // <1>
public class AuthenticationProviderUserPassword implements AuthenticationProvider<HttpRequest<?>> {
```

We did this change here: https://github.com/micronaut-projects/micronaut-security/pull/1320/files#top

Look for interfaces in that PR. 

We have done the same in Micronaut Views. 

We have this PR: https://github.com/micronaut-projects/micronaut-views/pull/522

**Comment by jeremyg484** [comment]
Closing this as resolved by #82, but note the linked issues to offshoot issues requiring slight variations on this approach.
