### ISSUE TITLE
annotation processors for core should use micronaut.core.version 

### ISSUE THREAD

**Issue by sdelamo** [openrewrite/rewrite-micronaut#77]
Core annotation processors, annotation processors whose group id is `io.micronaut`, should use  `<version>${micronaut.core.version}</version>`

```xml
<path>
              <groupId>io.micronaut</groupId>
              <artifactId>micronaut-inject-java</artifactId>
              <version>${micronaut.core.version}</version>
            </path>
            <path>
              <groupId>io.micronaut</groupId>
              <artifactId>micronaut-graal</artifactId>
              <version>${micronaut.core.version}</version>
            </path>
            <path>
              <groupId>io.micronaut</groupId>
              <artifactId>micronaut-http-validation</artifactId>
              <version>${micronaut.core.version}</version>
            </path>
```

**Comment by jeremyg484** [comment]
@sdelamo Heads up that it looks like micronaut-http-validation is using ${micronaut.version} in starter:

https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_17&lang=JAVA&build=MAVEN&test=JUNIT&features=data-jpa&features=micronaut-http-validation&version=4.0.0&activity=preview&showing=/pom.xml

**Comment by sdelamo** [comment]
> @sdelamo Heads up that it looks like micronaut-http-validation is using ${micronaut.version} in starter:
> 
> https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_17&lang=JAVA&build=MAVEN&test=JUNIT&features=data-jpa&features=micronaut-http-validation&version=4.0.0&activity=preview&showing=/pom.xml

Thanks, I have [created an issue](https://github.com/micronaut-projects/micronaut-starter/issues/1968). Please create an issue and add it to the project the next time.
