### ISSUE TITLE
maven property  micronaut.data.version

### ISSUE THREAD

**Issue by sdelamo** [openrewrite/rewrite-micronaut#78]
For Maven users with : 

```
    <micronaut.data.version>3.10.0</micronaut.data.version>
```

we need to update to: 

```xml
    <micronaut.data.version>4.0.1</micronaut.data.version>
```

Not sure if we can remove it which will be easier.

**Comment by alvarosanchez** [comment]
Do we generate this property in starter? It isn't needed

**Comment by alvarosanchez** [comment]
Yeah it seems we do. It needs to be removed there too

**Comment by sdelamo** [comment]
@jeremyg484 update the recipe to remove `micronaut.data.version` if exists in the maven project. 

@alvarosanchez I will create an issue for starter.
