### ISSUE TITLE
Migration to Micronaut 4 hasn't updated build.gradle.kts

### ISSUE THREAD

**Issue by sergey-morenets** [openrewrite/rewrite-micronaut#96]
## What version of OpenRewrite are you using?

I am using

- Gradle 8.4
- Gradle plugin 6.3.18
- rewrite-micronaut 2.1.4
- JDK 21

We tried to migrate our Micronaut 3.x project to Micronaut 4 using guidelines from this tutorial: https://micronaut.io/2023/07/14/upgrade-to-micronaut-framework-4-with-openrewrite-and-gradle/

However after we run this command: gradle rewriteDryRun the patch file contains only changes in two categories:

1) Rename javax.* -> jakarta.*
2) Remove withJansi element from logback.xml

The log contains strange lines:

```
 [WARN] [org.openrewrite.gradle.isolated.DefaultProjectParser] There were problems parsing some source files, run with --info to see full stack traces
[WARN] [org.openrewrite.gradle.isolated.DefaultProjectParser] There were problems parsing <some java file>
```

We re-ran the build using --info or --debug arguments however console didn't contain any stack errors or error descriptions.
So main issue is that migration didn't touch build.gradle.kts and missed a lot important steps (updating versions, dependencies, plugins, etc).

**Comment by timtebeek** [comment]
Could you share how you've configured OpenRewrite? And which command you're using to run? Those questions should have been in the issue template, and help us debug.

We don't yet support updating gradle kotlin files; support for that is tracked here:
- https://github.com/openrewrite/rewrite/issues/3291

We also have a recipe specifically to identify parse failures:
- https://docs.openrewrite.org/recipes/core/findparsefailures

Does running that recipe turn up any indications of where the parser might go wrong? We would be very interested to hear and improve the parser!

**Comment by sergey-morenets** [comment]
Hi @timtebeek 

Thank you for the quick response.
I used the instructions from the mentioned tutorial. They are also written here: https://docs.openrewrite.org/recipes/java/micronaut/micronaut3to4migration

```
plugins {
    id("org.openrewrite.rewrite") version("6.3.18")
}

rewrite {
    activeRecipe("org.openrewrite.java.micronaut.Micronaut3to4Migration")
}

repositories {
    mavenCentral()
}

dependencies {
    rewrite("org.openrewrite.recipe:rewrite-micronaut:2.1.4")
}
```

I also used **gradle rewriteDryRun** command to generate OpenRewrite patch. If you tell that you still don't support modifying Kotlin build scripts I guess it should be mentioned somewhere in the recipe description as limitation.

I also tried to use FindParseFailures recipe:

```
rewrite {     
    activeRecipe("org.openrewrite.FindParseFailures")
}
```

And here's output from the patch file:

```
@@ -1,4 +1,5 @@ org.openrewrite.config.CompositeRecipe
-package repository;
+(java.lang.IllegalStateException: repository\MongoSyncPaymentRepository.java is not print idempotent.
+  org.openrewrite.Parser.requirePrintEqualsInput(Parser.java:51))package repository;
 
 import static com.mongodb.client.model.Filters.eq;
```

**Comment by timtebeek** [comment]
Is there anything in `MongoSyncPaymentRepository` that you feel might trip up our parser? How much of that can you share or move into a reproduction sample? We'd very much like to fix any issues in our parser, as these are rare but affect our ability to make changes.

As for the Gradle kotlin build files; we'll track that in https://github.com/openrewrite/rewrite/issues/3291 as a limitation of OpenRewrite as a whole, not specific to this particular Micronaut migration recipe. Hope to be able to resolve that shortly, and ideally then only have to close that issue rather than also have to update references to that limitation elsewhere.

**Comment by timtebeek** [comment]
We'll track support for changing Gradle Kotlin Script files separately in
- https://github.com/openrewrite/rewrite/issues/3291

If you'd like to see the parse issues resolved it's best to open a separate issue and share the details there.

Thanks again for using OpenRewrite and reporting your findings here!
